### ISSUE TITLE
Sample code outdated and not consistent with documentation

### ISSUE THREAD

**Issue by monzol** [Adyen/adyen-secured-fields-sample-code#3]
Hi,

I was trying to learn from the sample code but realised that it's using an old JS libary where the setup object configuration is not compatible with the latest version. The sample uses checkoutSecuredFields.1.0.js while the latest version seems to be checkoutSecuredFields.1.3.0.js.

I also found that that the README.md refers to a documentation that no longer exists (https://docs.adyen.com/developers/secured-fields) and it redirects to a less relevant and less detailed documentation.

Would it be possible to bring this code up to date and have a dedicated documentation for 'Secured Fields'? 

Currently I find it difficult and time consuming to piece together info that I need on Secured Fields.

Thanks and regards,
Zoltan

**Comment by sponglord** [comment]
The sample code & documentation should now all be up to date
